/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Schema for policy/base.yml and policy/profiles/*.yml (v1)
 */
export interface CDNSecurityFrameworkPolicy {
  version: 1;
  project?: string;
  /**
   * Optional profile / policy metadata. `risk_level` hints the intended security posture — `permissive` triggers a build-time warning so operators do not accidentally ship a loose policy to production.
   */
  metadata?: {
    /**
     * Intended posture: strict, balanced, or permissive. Build warns on permissive and can be hard-failed with --fail-on-permissive.
     */
    risk_level?: "strict" | "balanced" | "permissive";
    description?: string;
    owner?: string;
  };
  defaults?: {
    mode?: "enforce" | "monitor";
    response?: {
      add_security_headers?: boolean;
    };
  };
  request: {
    allow_methods: string[];
    /**
     * Optional Host header allowlist. When set, requests whose Host does not match any entry are rejected at the edge. Entries support exact match (api.example.com) and wildcard prefix (*.example.com).
     */
    allowed_hosts?: string[];
    /**
     * If false (default), any client-supplied X-Forwarded-For header is stripped before the request reaches origin auth / logging. Enable only when the edge sits behind a trusted upstream proxy that you intentionally want to honor.
     */
    trust_forwarded_for?: boolean;
    limits?: {
      /**
       * Maximum querystring length in bytes. Requests exceeding this are rejected at the edge.
       */
      max_query_length?: number;
      /**
       * Maximum number of querystring keys. Protects against HTTP parameter pollution and cache poisoning.
       */
      max_query_params?: number;
      /**
       * Maximum request URI (path + query) length in bytes.
       */
      max_uri_length?: number;
      /**
       * Maximum individual request header value size in bytes.
       */
      max_header_size?: number;
      /**
       * Maximum number of request headers allowed at the edge. Protects origin parsers from hash-collision / amplification under small-but-many-headers payloads. Exceeding this returns 431 (Request Header Fields Too Large). Default 64.
       */
      max_header_count?: number;
    };
    /**
     * Optional lightweight request anomaly guards. When enabled, supported edge targets reject CRLF indicators in URI/query/header values, malformed Cookie headers, and bounded double-encoded traversal indicators before origin forwarding.
     */
    anomaly_guards?: {
      /**
       * Enable request anomaly guards. Individual checks default to enabled unless explicitly set to false.
       */
      enabled?: boolean;
      /**
       * Reject raw CR/LF characters and encoded %0d/%0a indicators in request URI, query, or header values.
       */
      crlf?: boolean;
      /**
       * Reject Cookie headers with control characters, empty delimiter segments, missing name/value delimiters, or configured size/pair-count overages.
       */
      malformed_cookie?: boolean;
      /**
       * Reject double-encoded traversal indicators such as %252e%252e, %252f, and %255c using at most one extra decode pass when %25 is present.
       */
      double_encoded_traversal?: boolean;
      /**
       * Maximum Cookie header length accepted by the malformed-cookie guard. Default 4096.
       */
      max_cookie_bytes?: number;
      /**
       * Maximum number of semicolon-delimited Cookie pairs accepted by the malformed-cookie guard. Default 80.
       */
      max_cookie_pairs?: number;
    };
    block?: {
      path_patterns?:
        | string[]
        | {
            contains?: string[];
            regex?: string[];
          };
      ua_contains?: string[];
      header_missing?: string[];
    };
    normalize?: {
      drop_query_keys?: string[];
      path?: {
        collapse_slashes?: boolean;
        remove_dot_segments?: boolean;
      };
    };
    /**
     * Optional GraphQL request guard for body-readable targets such as Cloudflare Workers. AWS CloudFront Functions/Lambda@Edge output cannot read request bodies and emits an unsupported warning when this is configured.
     */
    graphql_guard?: {
      /**
       * GraphQL endpoint path prefixes. Defaults to ["/graphql"] when omitted.
       *
       * @minItems 1
       */
      endpoint_paths?: [string, ...string[]];
      /**
       * Maximum selection-set nesting depth accepted by the lightweight scanner.
       */
      max_depth?: number;
      /**
       * Maximum number of field aliases accepted in one GraphQL document.
       */
      max_aliases?: number;
      /**
       * Maximum number of field names accepted in one GraphQL document.
       */
      max_fields?: number;
      /**
       * Maximum request body bytes the edge will read for GraphQL inspection. Defaults to 65536.
       */
      max_body_bytes?: number;
      /**
       * `block` rejects violating requests; `report` logs the violation and forwards the request.
       */
      mode?: "block" | "report";
    };
  };
  routes?: {
    name: string;
    match: {
      path_prefixes?: string[];
    };
    auth_gate?: {
      type?: "static_token" | "basic_auth" | "jwt" | "signed_url";
      header?: string;
      token_env?: string;
      credentials_env?: string;
      algorithm?: "HS256" | "RS256" | "ES256" | "HMAC-SHA256";
      /**
       * Optional whitelist of JWT header `alg` values accepted at verify time. If omitted, only the gate's configured `algorithm` is accepted. `none` is always rejected.
       */
      allowed_algorithms?: ("HS256" | "RS256" | "ES256")[];
      /**
       * Tolerance (in seconds) applied to JWT exp/nbf checks. Default 30.
       */
      clock_skew_sec?: number;
      jwks_url?: string;
      issuer?: string;
      audience?: string;
      secret_env?: string;
      /**
       * TTL (seconds) for cached gate material (for example, JWKS responses). Bounded to 24h to force rotation windows.
       */
      cache_ttl_sec?: number;
      expires_param?: string;
      signature_param?: string;
      /**
       * If true, signed-URL gates require the request URI to exactly match a protected prefix. If false (default, back-compat), any URI under the prefix is acceptable — which lets an attacker replay a signature issued for one sibling path against another. Archetypes for sensitive downloads should always set `true`.
       */
      exact_path?: boolean;
      /**
       * Optional query-parameter name carrying a per-URL nonce (e.g. `nonce`). When set, the edge forwards the nonce to origin as `X-Signed-URL-Nonce` so origin can enforce single-use (SET NX in Redis / KV). The edge alone cannot enforce replay protection — origin cooperation is required. See docs/signed-urls.md.
       */
      nonce_param?: string;
    };
    response?: {
      cache_control?: string;
    };
    request?: {
      allow_methods?: string[];
    };
  }[];
  response_headers: {
    hsts?: string;
    x_content_type_options?: string;
    referrer_policy?: string;
    permissions_policy?: string;
    csp_public?: string;
    csp_admin?: string;
    /**
     * CSP value to emit in Content-Security-Policy-Report-Only header for staged rollout. Pair with csp_report_uri. Browsers will warn but not block violations — use to validate policy before setting csp_public/csp_admin.
     */
    csp_report_only?: string;
    /**
     * URL for CSP violation reports. Emitted as `report-uri` directive if set. Prefer report-to + Reporting-Endpoints for modern browsers.
     */
    csp_report_uri?: string;
    /**
     * Generate a per-response nonce and substitute `'nonce-PLACEHOLDER'` in csp_public / csp_admin with the value. The nonce is also exposed as `x-csp-nonce` response header so origin templates can reference it. Cloudflare uses crypto.getRandomValues; CFF falls back to Math.random (lower entropy; documented).
     */
    csp_nonce?: boolean;
    /**
     * Cross-Origin-Opener-Policy. Together with COEP, isolates the browsing context and re-enables SharedArrayBuffer / high-precision timers. `same-origin` is the strict default.
     */
    coop?: "same-origin" | "same-origin-allow-popups" | "unsafe-none";
    /**
     * Cross-Origin-Embedder-Policy. `require-corp` blocks embedding of any cross-origin resource that does not explicitly opt in via CORP. `credentialless` is a softer alternative for third-party subresources.
     */
    coep?: "require-corp" | "credentialless" | "unsafe-none";
    /**
     * Cross-Origin-Resource-Policy. Controls whether other origins may embed this resource.
     */
    corp?: "same-origin" | "same-site" | "cross-origin";
    /**
     * Value for the Reporting-Endpoints header (e.g., `csp-endpoint="https://example.com/csp"`). Used with `report-to` directive in CSP.
     */
    reporting_endpoints?: string;
    /**
     * When true (default), every path covered by any auth gate receives `Cache-Control: no-store, no-cache, must-revalidate` + `Vary: Authorization, Cookie` at viewer-response. Prevents CDN edge caches from serving one user's authenticated response to another. Set false only if you understand the cache-poisoning risk (e.g., all protected responses are user-independent, such as prerendered public dashboards).
     */
    force_vary_auth?: boolean;
    /**
     * Paths on which to emit `Clear-Site-Data: "cache", "cookies", "storage"` + force `Cache-Control: no-store`. Use for logout / session-invalidation endpoints so the browser drops cached data even if the origin response is cached. Entries are prefix-matched (match when URI equals or starts with prefix + `/`). Only applied on 2xx and 3xx responses to avoid clobbering failed logouts.
     */
    clear_site_data_paths?: string[];
    /**
     * Override the default directive set for Clear-Site-Data. Default: `["cache","cookies","storage"]`. `executionContexts` forces the browser to reload the top-level frame and every same-origin frame.
     */
    clear_site_data_types?: ("cache" | "cookies" | "storage" | "executionContexts" | "*")[];
    cors?: {
      [k: string]: unknown;
    };
    cookie_attributes?: {
      secure?: boolean;
      http_only?: boolean;
      same_site?: "Strict" | "Lax" | "None";
    };
  };
  /**
   * Optional response DLP guard. Cloudflare Workers can inspect configured response headers and bounded text-like bodies; AWS CloudFront Functions cannot inspect response bodies and emit an unsupported warning.
   */
  response_dlp?: {
    enabled?: boolean;
    /**
     * `report_only` logs findings without mutation, `mask` replaces matched values, and `block` returns a synthetic blocked response.
     */
    action?: "report_only" | "mask" | "block";
    mask?: string;
    block_status?: number;
    block_body?: string;
    body?: {
      enabled?: boolean;
      /**
       * Maximum response body size to inspect on Cloudflare Workers. Larger bodies are passed through unmodified.
       */
      max_bytes?: number;
      /**
       * Lowercase substring allowlist for text-like Content-Type values eligible for body inspection.
       */
      content_types?: string[];
    };
    headers?: {
      enabled?: boolean;
      /**
       * Response header names to inspect and optionally mask/block.
       */
      names?: string[];
    };
    detectors?: {
      /**
       * Built-in high-confidence detectors. `credit_card` requires a Luhn-valid 13-19 digit candidate.
       */
      built_in?: ("api_key" | "credit_card")[];
      /**
       * Custom response detectors. Patterns are compiled at build time, capped to 256 characters, and rejected for nested-quantifier ReDoS shapes.
       *
       * @maxItems 10
       */
      custom_regex?:
        | []
        | [
            {
              name: string;
              pattern: string;
            }
          ]
        | [
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            }
          ]
        | [
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            }
          ]
        | [
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            }
          ]
        | [
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            }
          ]
        | [
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            }
          ]
        | [
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            }
          ]
        | [
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            }
          ]
        | [
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            }
          ]
        | [
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            },
            {
              name: string;
              pattern: string;
            }
          ];
    };
  };
  firewall?: {
    waf?: {
      /**
       * Per-IP request ceiling over the 5-minute WAF rate-based window. AWS WAFv2 accepts 100..2,000,000,000. Legacy single global rule; prefer `rate_limit_rules` for per-route / per-key controls.
       */
      rate_limit?: number;
      /**
       * Fine-grained rate-limit rules. Each entry renders as one `aws_wafv2_rule_group` rule with its own `rate_based_statement` and optional `scope_down_statement` so you can scope by URI, auth state, or header keys without hand-editing Terraform. `limit` is per 5-minute window (AWS WAFv2 accepts 100..2,000,000,000). `aggregate_key_type` defaults to `IP`; `FORWARDED_IP` follows the `X-Forwarded-For` chain and `CUSTOM_KEYS` lets you pass a raw `custom_keys` block. `scope_down_statement` is forwarded verbatim as a raw JSON object — schema-free because AWS WAFv2 ships dozens of statement kinds; lint only checks the shell.
       */
      rate_limit_rules?: {
        name: string;
        limit: number;
        aggregate_key_type?: "IP" | "FORWARDED_IP" | "CUSTOM_KEYS";
        custom_keys?: {
          [k: string]: unknown;
        }[];
        /**
         * Explicit Cloudflare expression for this rate-limit rule. Use when scope_down_statement cannot be translated safely.
         */
        expression_cloudflare?: string;
        /**
         * Cloudflare rate-limit characteristics used when aggregate_key_type is CUSTOM_KEYS.
         *
         * @minItems 1
         */
        cloudflare_characteristics?: [string, ...string[]];
        scope_down_statement?: {
          [k: string]: unknown;
        };
        priority?: number;
        action?: "block" | "count" | "captcha";
      }[];
      scope?: "REGIONAL" | "CLOUDFRONT";
      /**
       * AWS WAFv2 managed rule group names (vendor: AWS). Common pick-list: AWSManagedRulesCommonRuleSet (core OWASP Top 10), AWSManagedRulesKnownBadInputsRuleSet, AWSManagedRulesSQLiRuleSet, AWSManagedRulesLinuxRuleSet, AWSManagedRulesUnixRuleSet, AWSManagedRulesBotControlRuleSet (bot scoring, paid), AWSManagedRulesATPRuleSet (account-takeover, paid, scope_down to /login recommended), AWSManagedRulesIPReputationList (reputation-blocked), AWSManagedRulesAnonymousIpList (Tor / open proxies). Lint warns when defaults.mode == enforce and none of BotControl / ATP / IPReputation / AnonymousIp appear in the array. Entries not in the recommended set still compile — free-form string is intentional so you can opt into vendor additions without a framework release.
       */
      managed_rules?: string[];
      /**
       * Custom response body attached to every WAF rule whose action is `block`. AWS WAFv2 uses `custom_response_bodies` on the web ACL and references it with `custom_response_body_key` on the block action. Set `status_code` to override the default 403. When omitted, AWS WAFv2 returns its own 403 page (which leaks the CDN vendor).
       */
      block_response?: {
        status_code?: number;
        body?: string;
        content_type?: "TEXT_PLAIN" | "TEXT_HTML" | "APPLICATION_JSON";
      };
      /**
       * WAF logging configuration. When `enabled: true`, the compiler emits an `aws_wafv2_logging_configuration` block targeting `destination_arn_env` (env-backed Terraform variable reference). `redacted_fields` drops sensitive request fields from the log record — `authorization`, `cookie`, `x-api-key`, and `set-cookie` are the usual candidates. Lint warns when `scope == CLOUDFRONT` and logging is disabled because compliance frameworks (PCI-DSS, SOC2) require WAF log retention.
       */
      logging?: {
        enabled?: boolean;
        destination_arn_env?: string;
        redacted_fields?: ("authorization" | "cookie" | "set-cookie" | "x-api-key" | "x-csrf-token")[];
      };
      ja3_fingerprints?: string[];
      ja4_fingerprints?: string[];
      fingerprint_action?: "block" | "count";
    };
    /**
     * Experimental Cloudflare Workers-only JavaScript challenge / lightweight proof-of-work primitive. Opt in only after reviewing accessibility and false-positive impact. AWS CloudFront Functions / Lambda@Edge targets emit an unsupported warning because they cannot reliably serve and verify an HTML challenge response in this framework.
     */
    challenge?: {
      enabled?: boolean;
      /**
       * `report` logs matching traffic and allows it, `block` denies matching traffic, and `challenge` serves an HTML JS proof-of-work page until a valid cookie is set.
       */
      mode?: "report" | "block" | "challenge";
      /**
       * Request path prefixes that should trigger the challenge policy.
       */
      path_prefixes?: string[];
      /**
       * Case-insensitive User-Agent substrings that should trigger the challenge policy.
       */
      ua_contains?: string[];
      /**
       * Number of leading SHA-256 hex zeroes required in SHA-256(seed:nonce). Keep low; this is a lightweight friction primitive, not CAPTCHA.
       */
      difficulty?: number;
      /**
       * Lifetime of the solved challenge cookie. Default 900 seconds.
       */
      ttl_sec?: number;
      /**
       * Cloudflare Worker runtime env var containing the HMAC secret used to sign challenge seeds and cookies. Default CHALLENGE_SECRET.
       */
      secret_env?: string;
      /**
       * Cookie name for solved challenges. Default __cdn_challenge.
       */
      cookie_name?: string;
    };
    geo?: {
      block_countries?: string[];
      allow_countries?: string[];
    };
    ip?: {
      allowlist?: string[];
      blocklist?: string[];
    };
    /**
     * JWKS outbound-fetch guardrails. When `allowed_hosts` is set, the build refuses any JWT gate whose `jwks_url` hostname is not on the list, preventing SSRF into internal metadata endpoints. Regardless of this setting, the compiler also rejects non-HTTPS URLs and URLs that resolve to loopback, private, or link-local literals.
     */
    jwks?: {
      /**
       * Exact-match hostname allowlist for any `routes[].auth_gate.jwks_url`. Comparison is case-insensitive. Wildcards are not supported — list each IdP host explicitly.
       */
      allowed_hosts?: string[];
      /**
       * Window (seconds, default 3600, max 86400) to keep serving an expired JWKS cache entry if a refresh fails. Protects against IdP outages causing 100% auth failure. Set to 0 to disable.
       */
      stale_if_error_sec?: number;
      /**
       * TTL (seconds, default 60, max 600) for caching JWKS fetch failures to avoid hammering a broken IdP with retries. Set to 0 to disable.
       */
      negative_cache_sec?: number;
    };
  };
  transport?: {
    tls?: {
      minimum_version?: "TLSv1.2" | "TLSv1.3";
      security_policy?: string;
    };
    http?: {
      versions?: ("http1.1" | "http2" | "http3")[];
    };
  };
  /**
   * Edge log emission + correlation ID propagation. JSON format lets CloudWatch Logs Insights / Cloudflare Logpush parse fields directly. Issue #21, #22.
   */
  observability?: {
    /**
     * `json` (default) emits structured JSON on every block / monitor path. `text` keeps the legacy unstructured `[monitor] <code> <msg>` shape for backward compatibility.
     */
    log_format?: "json" | "text";
    /**
     * Incoming request header that carries a trace / correlation ID. Common values: `traceparent` (W3C Trace Context), `x-request-id`. The value is copied into log records and forwarded to origin so you can pivot from edge logs to app logs.
     */
    correlation_id_header?: string;
    /**
     * Fraction of allow-path requests that emit an `event:"allow"` log record (0 disables; 1 logs every request). Block-path logs always emit. Default 0.
     */
    sample_rate?: number;
    /**
     * When true, every successful auth gate pass emits `{event:"auth_pass", gate_name, sub, uri, method}`. Off by default — enable for security incident response. Raw tokens are never logged.
     */
    audit_log_auth?: boolean;
    /**
     * When true and `audit_log_auth` is enabled, `sub` is hashed (SHA-256 hex, first 16 chars) before emission to avoid PII in logs.
     */
    audit_hash_sub?: boolean;
  };
  origin?: {
    /**
     * Origin authentication injected by the edge runtime. `custom_header` forwards a static shared-secret header. `hmac_signature` signs method/path/query/body-hash/timestamp/nonce components with HMAC-SHA256 and emits derived headers under `header_prefix`. Secret values are always referenced by env var name only. See docs/origin-auth.md.
     */
    auth?: {
      [k: string]: unknown;
    };
    timeout?: {
      /**
       * Origin connect timeout in seconds. CloudFront caps this at 10s.
       */
      connect?: number;
      /**
       * Origin read/response timeout in seconds. CloudFront caps this at 60s.
       */
      read?: number;
    };
  };
}
